### ISSUE TITLE
favicon don't load

### ISSUE THREAD

**Issue by omnigenous** [micahmo/searxng-favicons#2]
```
Content-Security-Policy: The page’s settings blocked the loading of a resource (img-src) at https://www.google.com/s2/favicons?domain=https://en.wikipedia.org/wiki/Test&sz=20 because it violates the following directive: “img-src 'self' data: https://*.tile.openstreetmap.org”
```

**Comment by micahmo** [comment]
What instance are you using and what was your search term?

**Comment by omnigenous** [comment]
@micahmo https://searx.hu/search?q=test&language=auto&time_range=&safesearch=1&categories=general

But I have tried different instances, same exact thing happens.

**Comment by micahmo** [comment]
Unfortunately this seems to be a setting from the site owner to specifically block any image requests outside of their domain. The weird thing is that I can't find the `Content-Security-Policy` in their HTML (but I am not an expert in this area).

I did find a few instances on searx.space that allow remote image loading (I didn't try them all so there are probably several more). And it works on my private instance, so if you set up your own, the same is probably true.
* https://search.reallyaweso.me
* https://search.hbubli.cc
* https://search.incogniweb.net

This further reinforces that it is a site-specific thing. As an extension, I don't think I can bypass the security policy of the site.

**Comment by omnigenous** [comment]
@micahmo That makes sense, should probably put a notice in addon description and link this issue.

On a side note, would be nice to have a little spacing between favicon and site url.

**Comment by micahmo** [comment]
Thanks for the suggestion!

> would be nice to have a little spacing between favicon and site url.

I see space on my instance. What instance are you using? They may have slightly different HTML.

| ![image](https://github.com/micahmo/searxng-favicons/assets/7417301/c6dea067-7467-42b9-acfe-8fdabafbca11) |
| - |

**Comment by omnigenous** [comment]
@micahmo oh, it's only https://search.incogniweb.net that has no space.

**Comment by micahmo** [comment]
If it's only the one instance, I might not spend too much time trying to fix it. 😆 Thanks for the reports though!!
